/* SPDX-License-Identifier: BSD-2-Clause */
/*
 * TracePilot — Frame-Centric eBPF Scheduling + System Behavior Observatory
 *
 * Step 1: Collect sched_switch/sched_wakeup, irq_handler_entry/exit, and
 *         softirq_entry/exit events via tp_btf, align them to Perfetto
 *         FrameTimeline windows, and score threads by their contribution
 *         to jank — discounted for system overhead (IRQ/SoftIRQ).
 *
 * Usage:
 *   tracepilot --package <pkg> --duration <sec> \
 *              --frame-data <json> --output <json> \
 *              [--top-k <n>] [--events-out <bin>] [--debug]
 *
 * The skeleton header (tracepilot.skel.h) is generated by bpftool:
 *   bpftool gen skeleton output/tracepilot.bpf.o > loader/tracepilot.skel.h
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <signal.h>
#include <unistd.h>
#include <errno.h>
#include <getopt.h>
#include <time.h>
#include <sys/resource.h>

#include "libbpf/src/libbpf.h"
//#include "tracepilot.skel.h"

#include "frame_aggregator.h"
#include "resolver.h"
#include "../bpf/tracepilot.bpf.h"

/* ---- CLI defaults ---- */
#define DEFAULT_DURATION_S  30
#define DEFAULT_TOP_K       10

static volatile sig_atomic_t g_exiting = 0;

/* ---- Event store (dynamic arrays) ---- */
#define EVENTS_CHUNK 65536
#define EVENTS_MAGIC  0x32765054U /* "TPv2" little-endian */

struct events_file_header {
	uint32_t magic;
	uint32_t version;
	uint64_t sched_count;
	uint64_t sys_count;
};

static struct sched_event  *g_events     = NULL;
static size_t               g_events_cap = 0;
static size_t               g_events_cnt = 0;

static struct system_event *g_sys_events     = NULL;
static size_t               g_sys_events_cap = 0;
static size_t               g_sys_events_cnt = 0;

/* ---- CLI flags ---- */
static const char *g_package    = NULL;
static int         g_duration_s = DEFAULT_DURATION_S;
static const char *g_frame_data = NULL;
static const char *g_output     = NULL;
static const char *g_events_out = NULL;
static const char *g_events_in  = NULL;
static int         g_top_k      = DEFAULT_TOP_K;
static int         g_debug      = 0;

static void sig_handler(int sig)
{
	(void)sig;
	g_exiting = 1;
}

static void print_usage(const char *prog)
{
	fprintf(stderr,
		"Usage: %s [OPTIONS]\n"
		"Options:\n"
		"  -p, --package NAME     Target app package name (for display)\n"
		"  -d, --duration SEC     Collection duration in seconds (default: %d)\n"
		"  -f, --frame-data FILE  Frame data from Perfetto (trace_processor_shell output)\n"
		"  -o, --output FILE      Output JSON file for top-k results\n"
		"  -e, --events-out FILE  Save raw events to binary file\n"
		"  -i, --events-in FILE   Load raw events (offline mode, skip BPF collection)\n"
		"  -k, --top-k N          Number of top threads to output (default: %d)\n"
		"  -D, --debug            Enable debug output on stderr\n"
		"  -h, --help             Show this help\n"
		"\n"
		"On-device collection:\n"
		"  %s -d 30 -e events.bin -D\n"
		"\n"
		"Offline analysis (host):\n"
		"  %s -i events.bin -f frames.txt -o result.json\n"
		"\n",
		prog, DEFAULT_DURATION_S, DEFAULT_TOP_K, prog, prog);
}

static int parse_args(int argc, char **argv)
{
	static struct option long_opts[] = {
		{"package",    required_argument, 0, 'p'},
		{"duration",   required_argument, 0, 'd'},
		{"frame-data", required_argument, 0, 'f'},
		{"output",     required_argument, 0, 'o'},
		{"events-out", required_argument, 0, 'e'},
		{"events-in",  required_argument, 0, 'i'},
		{"top-k",      required_argument, 0, 'k'},
		{"debug",      no_argument,       0, 'D'},
		{"help",       no_argument,       0, 'h'},
		{0, 0, 0, 0}
	};

	int c;
	while ((c = getopt_long(argc, argv, "p:d:f:o:e:i:k:Dh", long_opts, NULL)) != -1) {
		switch (c) {
		case 'p': g_package    = optarg; break;
		case 'd': g_duration_s = atoi(optarg); break;
		case 'f': g_frame_data = optarg; break;
		case 'o': g_output     = optarg; break;
		case 'e': g_events_out = optarg; break;
		case 'i': g_events_in  = optarg; break;
		case 'k': g_top_k      = atoi(optarg); break;
		case 'D': g_debug      = 1; break;
		case 'h': print_usage(argv[0]); return -1;
		default:  print_usage(argv[0]); return -1;
		}
	}

	if (g_duration_s <= 0) {
		fprintf(stderr, "Invalid duration: %d\n", g_duration_s);
		return -1;
	}
	if (g_top_k <= 0) {
		fprintf(stderr, "Invalid top-k: %d\n", g_top_k);
		return -1;
	}

	return 0;
}

/* Store a copy of the event */
static void store_event(const struct sched_event *evt)
{
	if (g_events_cnt >= g_events_cap) {
		size_t new_cap = g_events_cap + EVENTS_CHUNK;
		struct sched_event *tmp = realloc(g_events, new_cap * sizeof(*g_events));
		if (!tmp) {
			fprintf(stderr, "realloc events failed, dropping event\n");
			return;
		}
		g_events = tmp;
		g_events_cap = new_cap;
	}
	g_events[g_events_cnt++] = *evt;
}

/* ring_buffer callback — called for each event from kernel */
static int handle_event(void *ctx, void *data, size_t data_sz)
{
	(void)ctx;

	if (data_sz != sizeof(struct sched_event)) {
		fprintf(stderr, "WARN: unexpected event size %zu (expected %zu)\n",
			data_sz, sizeof(struct sched_event));
		return 0;
	}

	const struct sched_event *evt = data;

	/* Filter by target package if specified */
	if (g_package) {
		char pkg[256] = {0};
		uint32_t pid;

		pid = evt->next_pid;

		if (pid > 0 && resolve_pid((pid_t)pid, pkg, sizeof(pkg)) == 0) {
			if (strcmp(pkg, g_package) != 0) {
				/* Check prev also */
				if (evt->event_type == EVENT_SCHED_SWITCH && evt->prev_pid > 0) {
					char pkg2[256] = {0};
					if (resolve_pid((pid_t)evt->prev_pid, pkg2, sizeof(pkg2)) != 0 ||
					    strcmp(pkg2, g_package) != 0)
						return 0;
				} else {
					return 0;
				}
			}
		}
	}

	store_event(evt);

	if (g_debug) {
		const char *type_str = evt->event_type == EVENT_SCHED_SWITCH ? "SW" : "WK";
		fprintf(stderr, "[DBG] %s ts=%llu prev=%u:%s next=%u:%s cpu=%u wl=%llu\n",
			type_str,
			(unsigned long long)evt->timestamp_ns,
			evt->prev_tid, evt->prev_comm,
			evt->next_tid, evt->next_comm,
			evt->cpu,
			(unsigned long long)evt->wakeup_latency_ns);
	}

	return 0;
}

/* ring_buffer callback for system events (IRQ/SoftIRQ) */
static int handle_sys_event(void *ctx, void *data, size_t data_sz)
{
	(void)ctx;

	if (data_sz != sizeof(struct system_event))
		return 0;

	const struct system_event *evt = data;

	if (g_sys_events_cnt >= g_sys_events_cap) {
		size_t new_cap = g_sys_events_cap + EVENTS_CHUNK;
		struct system_event *tmp = realloc(g_sys_events, new_cap * sizeof(*g_sys_events));
		if (!tmp)
			return 0;
		g_sys_events = tmp;
		g_sys_events_cap = new_cap;
	}
	g_sys_events[g_sys_events_cnt++] = *evt;

	if (g_debug) {
		const char *type = evt->event_type == SYS_EVENT_IRQ ? "IRQ" : "SFT";
		fprintf(stderr, "[DBG] %s vec=%d cpu=%u dur=%llu\n",
			type, evt->irq_vec, evt->cpu,
			(unsigned long long)evt->duration_ns);
	}
	return 0;
}

/* Save sched + system events to binary file (v2 format with header) */
static int save_events(const char *path)
{
	struct events_file_header hdr = {
		.magic       = EVENTS_MAGIC,
		.version     = 1,
		.sched_count = g_events_cnt,
		.sys_count   = g_sys_events_cnt,
	};
	FILE *fp = fopen(path, "wb");
	if (!fp) {
		perror("fopen events-out");
		return -1;
	}

	if (fwrite(&hdr, sizeof(hdr), 1, fp) != 1)
		goto write_err;

	if (g_events_cnt > 0) {
		if (fwrite(g_events, sizeof(struct sched_event), g_events_cnt, fp) != g_events_cnt)
			goto write_err;
	}
	if (g_sys_events_cnt > 0) {
		if (fwrite(g_sys_events, sizeof(struct system_event), g_sys_events_cnt, fp) != g_sys_events_cnt)
			goto write_err;
	}

	fclose(fp);
	if (g_debug)
		fprintf(stderr, "[DBG] saved %zu sched + %zu sys events to %s\n",
			g_events_cnt, g_sys_events_cnt, path);
	return 0;

write_err:
	perror("fwrite events");
	fclose(fp);
	return -1;
}

/* Load events from binary file (supports v1 raw and v2 header formats) */
static int load_events(const char *path)
{
	struct events_file_header hdr;
	FILE *fp = fopen(path, "rb");
	if (!fp) {
		perror("fopen events-in");
		return -1;
	}

	/* Try to read v2 header */
	if (fread(&hdr, sizeof(hdr), 1, fp) == 1 && hdr.magic == EVENTS_MAGIC) {
		/* ── v2 format: header + sched events + system events ── */
		if (hdr.sched_count > 0) {
			g_events_cnt = hdr.sched_count;
			g_events_cap = hdr.sched_count;
			g_events = malloc(g_events_cnt * sizeof(struct sched_event));
			if (!g_events) {
				fclose(fp);
				return -1;
			}
			if (fread(g_events, sizeof(struct sched_event), g_events_cnt, fp)
			    != g_events_cnt) {
				fprintf(stderr, "Failed to read sched events\n");
				fclose(fp);
				return -1;
			}
		}
		if (hdr.sys_count > 0) {
			g_sys_events_cnt = hdr.sys_count;
			g_sys_events_cap = hdr.sys_count;
			g_sys_events = malloc(g_sys_events_cnt * sizeof(struct system_event));
			if (!g_sys_events) {
				fclose(fp);
				return -1;
			}
			if (fread(g_sys_events, sizeof(struct system_event),
			          g_sys_events_cnt, fp) != g_sys_events_cnt) {
				fprintf(stderr, "Failed to read system events\n");
				fclose(fp);
				return -1;
			}
		}
		fclose(fp);
		if (g_debug)
			fprintf(stderr, "[DBG] loaded %zu sched + %zu sys events (v2)\n",
				g_events_cnt, g_sys_events_cnt);
		return 0;
	}

	/* ── v1 format (backward compat): entire file is raw sched events ── */
	fseek(fp, 0, SEEK_END);
	long sz = ftell(fp);
	rewind(fp);

	if (sz <= 0 || sz % (long)sizeof(struct sched_event) != 0) {
		fprintf(stderr, "Invalid events file size: %ld%s\n",
		        sz, sz == 0 ? " (empty file)" : "");
		fclose(fp);
		return -1;
	}

	g_events_cnt = sz / sizeof(struct sched_event);
	g_events_cap = g_events_cnt;
	g_sys_events_cnt = 0;
	g_events = malloc(sz);
	if (!g_events) {
		fclose(fp);
		return -1;
	}

	if (fread(g_events, sizeof(struct sched_event), g_events_cnt, fp) != g_events_cnt) {
		fprintf(stderr, "Failed to read events\n");
		fclose(fp);
		return -1;
	}
	fclose(fp);

	if (g_debug)
		fprintf(stderr, "[DBG] loaded %zu events (v1, no sys events)\n", g_events_cnt);
	return 0;
}

/* Run aggregation and output for events that were already collected */
static int run_analysis(void)
{
	struct frame_window *frames = NULL;
	int num_frames;
	FILE *out;
	size_t i;

	if (!g_frame_data) {
		fprintf(stderr, "No --frame-data provided, skipping analysis.\n");
		return 0;
	}

	num_frames = parse_frame_json(g_frame_data, &frames);
	if (num_frames < 0) {
		fprintf(stderr, "Failed to parse frame JSON: %s\n", g_frame_data);
		return -1;
	}
	if (g_debug)
		fprintf(stderr, "[DBG] parsed %d frames (%d jank)\n",
			num_frames,
			({ int c = 0; for (int j = 0; j < num_frames; j++) if (frames[j].is_jank) c++; c; }));

	frames_init(frames, num_frames);

	/* Auto-detect clock offset between eBPF (CLOCK_MONOTONIC) and
	   Perfetto (CLOCK_BOOTTIME) by aligning the earliest timestamps. */
	if (g_events_cnt > 0 && num_frames > 0) {
		uint64_t min_ebpf = g_events[0].timestamp_ns;
		uint64_t min_frame = frames[0].expected_start_ns;
		int64_t offset = (int64_t)(min_frame - min_ebpf);
		frames_set_clock_offset(offset);
		if (g_debug)
			fprintf(stderr, "[DBG] clock offset: %lld ns (frame=%llu ebpf=%llu)\n",
			        (long long)offset,
			        (unsigned long long)min_frame,
			        (unsigned long long)min_ebpf);
	}

	/* Aggregate system events (IRQ/SoftIRQ) FIRST — populate frame overhead
	   before sched events read it for thread scoring discount. */
	for (i = 0; i < g_sys_events_cnt; i++) {
		const struct system_event *evt = &g_sys_events[i];
		for (int j = 0; j < num_frames; j++) {
			accumulate_system_event(evt, &frames[j]);
		}
	}

	/* Aggregate all collected events against all jank frames */
	for (i = 0; i < g_events_cnt; i++) {
		const struct sched_event *evt = &g_events[i];
		for (int j = 0; j < num_frames; j++) {
			aggregate_event(evt, &frames[j]);
		}
	}

	/* Resolve package names for threads */
	for (i = 0; i < g_events_cnt; i++) {
		const struct sched_event *evt = &g_events[i];
		char pkg[256] = {0};

		if (evt->event_type == EVENT_SCHED_SWITCH) {
			/* Resolve next (switched-in) task */
			if (evt->next_pid > 0 &&
			    resolve_pid((pid_t)evt->next_pid, pkg, sizeof(pkg)) == 0) {
				frames_set_thread_info(evt->next_tid, evt->next_pid, pkg);
			}
			/* Resolve prev (preempted) task */
			if (evt->prev_pid > 0 &&
			    resolve_pid((pid_t)evt->prev_pid, pkg, sizeof(pkg)) == 0) {
				frames_set_thread_info(evt->prev_tid, evt->prev_pid, pkg);
			}
		} else {
			if (evt->next_pid > 0 &&
			    resolve_pid((pid_t)evt->next_pid, pkg, sizeof(pkg)) == 0) {
				frames_set_thread_info(evt->next_tid, evt->next_pid, pkg);
			}
		}
	}

	/* Output */
	if (g_output) {
		out = fopen(g_output, "w");
		if (!out) {
			perror("fopen output");
			free(frames);
			return -1;
		}
	} else {
		out = stdout;
	}

	output_topk(out, g_top_k);

	if (g_output)
		fclose(out);
	free(frames);
	return 0;
}

int main(int argc, char **argv)
{
	struct ring_buffer *rb = NULL;
	struct bpf_object *obj = NULL;
	struct bpf_program *prog;
	struct bpf_map *map;
	int err;

	if (parse_args(argc, argv) != 0)
		return 1;

	signal(SIGINT, sig_handler);
	signal(SIGTERM, sig_handler);

	if (g_events_in) {
		if (load_events(g_events_in) != 0)
			return 1;
		if (g_frame_data)
			run_analysis();
		else if (g_debug)
			fprintf(stderr, "[DBG] no --frame-data, skipping analysis\n");
		free(g_events);
		free(g_sys_events);
		return 0;
	}

	struct rlimit rlim = {RLIM_INFINITY, RLIM_INFINITY};
	setrlimit(RLIMIT_MEMLOCK, &rlim);

	{
		char dummy[256];
		resolve_pid(1, dummy, sizeof(dummy));
	}

	if (g_debug)
		fprintf(stderr, "[DBG] loading BPF object...\n");
obj = bpf_object__open_file("/data/local/tmp/tracepilot.bpf.o", NULL);
	if (!obj) {
		fprintf(stderr, "Failed to open BPF object: %d\n", errno);
		return 1;
	}

	err = bpf_object__load(obj);
	if (err) {
		fprintf(stderr, "Failed to load BPF object: %d\n", err);
		bpf_object__close(obj);
		return 1;
	}

	bpf_object__for_each_program(prog, obj) {
		bpf_program__attach(prog);
	}

	{
		struct bpf_map *m = bpf_object__find_map_by_name(obj, "events");
		if (!m) {
			fprintf(stderr, "Failed to find 'events' map\n");
			bpf_object__close(obj);
			return 1;
		}
		rb = ring_buffer__new(bpf_map__fd(m), handle_event, NULL, NULL);
	}

	{
		struct bpf_map *m = bpf_object__find_map_by_name(obj, "sys_events");
		if (m)
			ring_buffer__add(rb, bpf_map__fd(m), handle_sys_event, NULL);
	}

	time_t end = time(NULL) + g_duration_s;
	while (time(NULL) < end && !g_exiting)
		ring_buffer__poll(rb, 100);

	if (g_events_out && (g_events_cnt > 0 || g_sys_events_cnt > 0))
		save_events(g_events_out);

	if (g_frame_data)
		run_analysis();
	else if (g_debug)
		fprintf(stderr, "[DBG] no --frame-data, skipping analysis\n");

	free(g_events);
	free(g_sys_events);
	return 0;
}