#!/usr/bin/env python3
"""
TracePilot Task 17 — 训练脚本
读取人工标注的 CSV，训练决策树分类器，导出为 C 数组。

用法：
  python3 scripts/train_jank_model.py output/labels_all.csv

依赖：
  pip install scikit-learn numpy

输出：
  output/learned_model.h       — C 头文件（嵌入 loader）
  output/learned_model_info.txt — 模型性能报告
"""
import csv
import sys
import os
import numpy as np

try:
    from sklearn.tree import DecisionTreeClassifier, export_text
    from sklearn.model_selection import cross_val_score, LeaveOneOut
    from sklearn.metrics import classification_report, confusion_matrix
except ImportError:
    print("需要安装 scikit-learn: pip install scikit-learn")
    sys.exit(1)

FEATURES = [
    "runnable_delay",
    "binder_centrality",
    "futex_wait",
    "thermal_throttle",
    "decode_late",
    "system_irq",
]

CAUSE_MAP = {
    "RUNNABLE_DELAY": 0,
    "BINDER_BLOCKING": 1,
    "FUTEX_BLOCKING": 2,
    "THERMAL_THROTTLE": 3,
    "VIDEO_LATE_RENDER": 4,
    "IO_WAIT": 5,
    "MEMORY_RECLAIM": 6,
    "GPU_STALL": 7,
    "AUDIO_SYNC_DRIFT": 8,
    "CPU_CONTENTION": 9,
}

CAUSE_NAMES = list(CAUSE_MAP.keys())


def load_labeled_data(csv_path):
    X, y, meta = [], [], []
    with open(csv_path, encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            label = row.get("label", "").strip()
            if label not in CAUSE_MAP:
                continue
            features = [float(row.get(feat, 0.0)) for feat in FEATURES]
            X.append(features)
            y.append(CAUSE_MAP[label])
            meta.append(row.get("frame_id", ""))
    return np.array(X), np.array(y), meta


def train_and_evaluate(X, y):
    clf = DecisionTreeClassifier(
        max_depth=5,
        min_samples_leaf=2,
        class_weight="balanced",
        random_state=42,
    )
    clf.fit(X, y)

    n_samples = len(y)
    if n_samples >= 10:
        cv = min(5, n_samples)
        scores = cross_val_score(clf, X, y, cv=cv, scoring="accuracy")
        cv_acc = scores.mean()
        cv_std = scores.std()
    else:
        cv_acc = None
        cv_std = None

    y_pred = clf.predict(X)
    labels_present = sorted(set(y) | set(y_pred))
    target_names_present = [CAUSE_NAMES[i] for i in labels_present]
    report = classification_report(y, y_pred, labels=labels_present,
                                   target_names=target_names_present, zero_division=0)
    cm = confusion_matrix(y, y_pred, labels=labels_present)
    tree_text = export_text(clf, feature_names=FEATURES, max_depth=4)

    return clf, cv_acc, cv_std, report, cm, tree_text


def export_c_header(clf, out_path):
    tree = clf.tree_
    n_nodes = tree.node_count
    feature = tree.feature
    threshold = tree.threshold
    value = tree.value
    children_left = tree.children_left
    children_right = tree.children_right

    lines = []
    lines.append("/* Auto-generated by train_jank_model.py — Task 17 Learned Policy */")
    lines.append("#ifndef __LEARNED_MODEL_H__")
    lines.append("#define __LEARNED_MODEL_H__")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append(f"#define LEARNED_TREE_NODES {n_nodes}")
    lines.append(f"#define LEARNED_FEATURES {len(FEATURES)}")
    lines.append(f"#define LEARNED_CLASSES {len(CAUSE_NAMES)}")
    lines.append("")
    lines.append("typedef struct {")
    lines.append("    int32_t  feature_idx;   /* -1 = leaf */")
    lines.append("    float    threshold;")
    lines.append("    int32_t  left;")
    lines.append("    int32_t  right;")
    lines.append("    int32_t  class_idx;     /* leaf only */")
    lines.append("    float    class_prob[LEARNED_CLASSES];")
    lines.append("} learned_node_t;")
    lines.append("")
    lines.append("static const learned_node_t learned_tree[LEARNED_TREE_NODES] = {")

    for i in range(n_nodes):
        is_leaf = children_left[i] == children_right[i]
        feat = -1 if is_leaf else int(feature[i])
        thresh = float(threshold[i]) if not is_leaf else 0.0
        left = int(children_left[i]) if not is_leaf else -1
        right = int(children_right[i]) if not is_leaf else -1
        cls_idx = int(np.argmax(value[i][0]))
        probs = value[i][0] / (value[i][0].sum() + 1e-10)
        prob_str = ", ".join(f"{p:.6f}f" for p in probs)
        lines.append(
            f"    {{ {feat:2d}, {thresh:12.6f}f, {left:4d}, {right:4d}, "
            f"{cls_idx}, {{ {prob_str} }} }},  /* node {i} */"
        )

    lines.append("};")
    lines.append("")
    lines.append("/* Feature index: 0=runnable_delay, 1=binder, 2=futex, 3=thermal, 4=decode, 5=irq */")
    lines.append("/* Class index: 0=RUNNABLE_DELAY, 1=BINDER_BLOCKING, 2=FUTEX_BLOCKING, */")
    lines.append("/*   3=THERMAL_THROTTLE, 4=VIDEO_LATE_RENDER, 5=IO_WAIT, */")
    lines.append("/*   6=MEMORY_RECLAIM, 7=GPU_STALL, 8=AUDIO_SYNC_DRIFT, 9=CPU_CONTENTION */")
    lines.append("")
    lines.append("static inline int learned_predict(const float *features) {")
    lines.append("    int node = 0;")
    lines.append("    while (learned_tree[node].feature_idx >= 0) {")
    lines.append("        if (features[learned_tree[node].feature_idx] <= learned_tree[node].threshold)")
    lines.append("            node = learned_tree[node].left;")
    lines.append("        else")
    lines.append("            node = learned_tree[node].right;")
    lines.append("    }")
    lines.append("    return learned_tree[node].class_idx;")
    lines.append("}")
    lines.append("")
    lines.append("#endif /* __LEARNED_MODEL_H__ */")
    lines.append("")

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def main():
    if len(sys.argv) < 2:
        print("用法: python3 train_jank_model.py <labels_all.csv> [output_dir]")
        sys.exit(1)

    csv_path = sys.argv[1]
    out_dir = sys.argv[2] if len(sys.argv) > 2 else os.path.dirname(csv_path)
    os.makedirs(out_dir, exist_ok=True)

    X, y, meta = load_labeled_data(csv_path)
    n_samples = len(y)
    print(f"加载 {n_samples} 条标注数据")
    print(f"类别分布: {dict(zip(CAUSE_NAMES, [int(np.sum(y == i)) for i in range(len(CAUSE_NAMES))]))}")

    if n_samples < 5:
        print("标注数据不足 5 条，无法训练。请继续标注。")
        sys.exit(1)

    unique_classes = np.unique(y)
    if len(unique_classes) < 2:
        print(f"只有 1 个类别（{CAUSE_NAMES[unique_classes[0]]}），无法训练分类器。")
        print("请用 suspect_frames.py 找出可疑帧，人工标注不同类别后重试。")
        print(f"已将单类别模型信息写入 {out_dir}/learned_model_info.txt")
        info_path = os.path.join(out_dir, "learned_model_info.txt")
        with open(info_path, "w", encoding="utf-8") as f:
            f.write("=== TracePilot Task 17 — Learned Policy Model ===\n\n")
            f.write(f"训练样本数: {n_samples}\n")
            f.write(f"单一类别: {CAUSE_NAMES[unique_classes[0]]}\n")
            f.write("需要更多样本来训练多类别分类器。\n")
        sys.exit(1)

    clf, cv_acc, cv_std, report, cm, tree_text = train_and_evaluate(X, y)

    info_path = os.path.join(out_dir, "learned_model_info.txt")
    with open(info_path, "w", encoding="utf-8") as f:
        f.write("=== TracePilot Task 17 — Learned Policy Model ===\n\n")
        f.write(f"训练样本数: {n_samples}\n")
        f.write(f"特征维度: {len(FEATURES)}\n")
        f.write(f"特征列表: {FEATURES}\n")
        f.write(f"类别数: {len(CAUSE_NAMES)}\n\n")
        if cv_acc is not None:
            f.write(f"交叉验证准确率: {cv_acc:.4f} ± {cv_std:.4f}\n\n")
        else:
            f.write("样本不足，跳过交叉验证\n\n")
        f.write("分类报告（训练集）:\n")
        f.write(report)
        f.write("\n混淆矩阵:\n")
        f.write(str(cm))
        f.write("\n\n决策树结构:\n")
        f.write(tree_text)
    print(f"模型信息 → {info_path}")

    h_path = os.path.join(out_dir, "learned_model.h")
    export_c_header(clf, h_path)
    print(f"C 头文件 → {h_path}")
    print("可在 loader 中 #include \"learned_model.h\" 使用 learned_predict() 函数")


if __name__ == "__main__":
    main()
