/* Auto-generated by train_jank_model.py — Task 17 Learned Policy */
#ifndef __LEARNED_MODEL_H__
#define __LEARNED_MODEL_H__

#include <stdint.h>

#define LEARNED_TREE_NODES 3
#define LEARNED_FEATURES 6
#define LEARNED_CLASSES 10

typedef struct {
    int32_t  feature_idx;   /* -1 = leaf */
    float    threshold;
    int32_t  left;
    int32_t  right;
    int32_t  class_idx;     /* leaf only */
    float    class_prob[LEARNED_CLASSES];
} learned_node_t;

static const learned_node_t learned_tree[LEARNED_TREE_NODES] = {
    {  0,    12.128000f,    1,    2, 0, { 0.500000f, 0.500000f } },  /* node 0 */
    { -1,     0.000000f,   -1,   -1, 0, { 1.000000f, 0.000000f } },  /* node 1 */
    { -1,     0.000000f,   -1,   -1, 1, { 0.000000f, 1.000000f } },  /* node 2 */
};

/* Feature index: 0=runnable_delay, 1=binder, 2=futex, 3=thermal, 4=decode, 5=irq */
/* Class index: 0=RUNNABLE_DELAY, 1=BINDER_BLOCKING, 2=FUTEX_BLOCKING, */
/*   3=THERMAL_THROTTLE, 4=VIDEO_LATE_RENDER, 5=IO_WAIT, */
/*   6=MEMORY_RECLAIM, 7=GPU_STALL, 8=AUDIO_SYNC_DRIFT, 9=CPU_CONTENTION */

static inline int learned_predict(const float *features) {
    int node = 0;
    while (learned_tree[node].feature_idx >= 0) {
        if (features[learned_tree[node].feature_idx] <= learned_tree[node].threshold)
            node = learned_tree[node].left;
        else
            node = learned_tree[node].right;
    }
    return learned_tree[node].class_idx;
}

#endif /* __LEARNED_MODEL_H__ */
