#!/usr/bin/env python3
"""
graph_export.py — 关键路径图可视化导出
==========================================
读取 critical_path_graph.json, 生成:
  - DOT 文件 (Graphviz)  → output/analysis/graph_topology.dot
  - 简化版: 仅 Top-K 线程的子图

用法:
  python graph_export.py
  python graph_export.py --top 5
  python graph_export.py --format svg
"""

import json, os, sys
from collections import defaultdict

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
GRAPH_JSON = os.path.join(BASE_DIR, "..", "output", "analysis", "critical_path_graph.json")
OUT_DIR = os.path.join(BASE_DIR, "..", "output", "analysis")

def role_color(role):
    """角色 → DOT 颜色"""
    colors = {
        "UI Thread":      "#9b59b6",  # 紫
        "RenderThread":   "#2980b9",  # 蓝
        "SurfaceFlinger": "#e74c3c",  # 红
        "Binder RPC":     "#3498db",  # 浅蓝
        "HwBinder RPC":   "#1abc9c",  # 青
        "GPU Worker":     "#27ae60",  # 绿
        "CameraThread":   "#f39c12",  # 橙
        "CameraHal":      "#e67e22",  # 深橙
        "CameraService":  "#d35400",  # 棕色
        "SystemService":  "#95a5a6",  # 灰
        "HwComposer":     "#8e44ad",  # 深紫
        "I/O Worker":     "#7f8c8d",  # 暗灰
        "KernelWorker":   "#bdc3c7",  # 浅灰
        "JpegEncoder":    "#2ecc71",  # 翠绿
        "MediaCodec":     "#16a085",  # 深绿
    }
    return colors.get(role, "#bdc3c7")

def export_dot(graph_data, output_path, max_nodes=30, label="Critical Path Graph", mode="full"):
    """导出完整图结构 (含 Frame/Thread/Resource 节点 + 所有边)"""
    meta = graph_data.get("meta", {})
    scores = graph_data.get("global_critical_scores", [])
    frames = graph_data.get("frames", [])

    top_tids = {s["tid"] for s in scores[:max_nodes]}

    lines = []
    lines.append("// Auto-generated by graph_export.py")
    lines.append("digraph CriticalPath {")
    lines.append(f'  label="{label}"; rankdir=LR;')
    lines.append('  node [shape=box, style=rounded];')
    lines.append("")

    # ── 节点: Frame + Resource + Thread ──
    if mode == "full":
        # 字段模式: 从所有帧收集节点
        all_nodes = {}
        for f_data in frames:
            for n in f_data.get("nodes", []):
                nid = n["id"]
                if nid not in all_nodes:
                    all_nodes[nid] = n

        for nid, n in all_nodes.items():
            ntype = n.get("type", "thread")
            if ntype == "frame":
                ft = n.get("frame_token", "?")
                lines.append(f'  {nid} [label="Frame {ft}", shape=box, style="filled,dashed", '
                             f'fillcolor="#ecf0f1", fontcolor=black];')
            elif ntype == "resource":
                label_text = n.get("label", "?")
                color = {"HardIRQ": "#e74c3c", "SoftIRQ": "#f39c12",
                         "CPUThrottle": "#3498db", "MemReclaim": "#8e44ad"}.get(label_text, "#95a5a6")
                lines.append(f'  {nid} [label="{label_text}\\n{n.get(\"overhead_ns\",0)/1e6:.1f}ms", '
                             f'fillcolor="{color}", style=filled, fontcolor=white, shape=cds];')
            else:
                tid_val = n.get("tid", 0)
                if tid_val not in top_tids:
                    continue
                comm = n.get("comm", "?")
                role_str = n.get("role", "")
                color = role_color(role_str)
                lines.append(f'  t{tid_val} [label="{comm}\\nTID:{tid_val}", '
                             f'fillcolor="{color}", style=filled, fontcolor=white];')

    else:
        # per-frame 模式: 只导出该帧的节点
        nid_set = set()
        for n in graph_data.get("nodes", []):
            ntype = n.get("type", "thread")
            nid = n["id"]
            if ntype == "frame":
                ft = n.get("frame_token", "?")
                lines.append(f'  {nid} [label="Frame {ft}", shape=box, style="filled,dashed", '
                             f'fillcolor="#ecf0f1", fontcolor=black];')
                nid_set.add(nid)
            elif ntype == "resource":
                label_text = n.get("label", "?")
                color = {"HardIRQ": "#e74c3c", "SoftIRQ": "#f39c12",
                         "CPUThrottle": "#3498db", "MemReclaim": "#8e44ad"}.get(label_text, "#95a5a6")
                lines.append(f'  {nid} [label="{label_text}\\n{n.get(\"overhead_ns\",0)/1e6:.1f}ms", '
                             f'fillcolor="{color}", style=filled, fontcolor=white, shape=cds];')
                nid_set.add(nid)
            else:
                tid_val = n.get("tid", 0)
                comm = n.get("comm", "?")
                role_str = n.get("role", "")
                color = role_color(role_str)
                lines.append(f'  t{tid_val} [label="{comm}\\nTID:{tid_val}", '
                             f'fillcolor="{color}", style=filled, fontcolor=white];')
                nid_set.add(nid)

        # 边
        for e in graph_data.get("edges", []):
            color = {"BINDER_CALL": "#e74c3c", "RUNNABLE_WAIT": "#3498db",
                     "FUTEX_WAIT": "#f39c12", "FRAME_DEPENDENCY": "#95a5a6",
                     "SYSTEM_OVERHEAD": "#e67e22", "RESOURCE_STALL": "#c0392b"}.get(e.get("type",""), "#999")
            label = e.get("type", "?")
            dur = e.get("duration_ns", 0)
            if dur > 0:
                label += f" {dur/1e6:.1f}ms"
            lines.append(f'  {e["src"]} -> {e["dst"]} [color="{color}", label="{label}"];')

    # ── 全局模式: 边 ──
    if mode == "full":
        edge_set = set()
        for f_data in frames:
            for e in f_data.get("edges", []):
                edge_set.add((e.get("src",""), e.get("dst",""), e.get("type","?"),
                              e.get("duration_ns", 0) or e.get("severity", 0)))
        for src, dst, etype, val in edge_set:
            color = {"BINDER_CALL": "#e74c3c", "RUNNABLE_WAIT": "#3498db",
                     "FUTEX_WAIT": "#f39c12", "FRAME_DEPENDENCY": "#95a5a6",
                     "SYSTEM_OVERHEAD": "#e67e22", "RESOURCE_STALL": "#c0392b"}.get(etype, "#999")
            label = etype
            if isinstance(val, (int, float)) and val > 0:
                label += f" {val/1e6:.1f}ms" if val > 1000 else f" {val:.2f}"
            lines.append(f'  {src} -> {dst} [color="{color}", label="{label}"];')

    lines.append("}")
    with open(output_path, "w") as f:
        f.write("\n".join(lines))
    n_nodes = lines.count('label="Frame') + lines.count('shape=cds') + lines.count('t')
    print(f"[✓] DOT exported: {output_path} ({n_nodes} nodes, {len(lines) - 3 - n_nodes} edges)")


def main():
    top_k = 15
    for i in range(1, len(sys.argv)):
        if sys.argv[i] == "--top" and i+1 < len(sys.argv):
            top_k = int(sys.argv[i+1])

    if not os.path.exists(GRAPH_JSON):
        print(f"[✗] {GRAPH_JSON} not found. Run analyze_delays.py first.")
        sys.exit(1)

    with open(GRAPH_JSON) as f:
        data = json.load(f)

    # 全局拓扑
    out_file = os.path.join(OUT_DIR, "graph_topology.dot")
    export_dot(data, out_file, max_nodes=top_k, mode="full")

    # 每帧子图 (含完整节点+边)
    frames_data = data.get("frames", [])
    print(f"[*] Exporting per-frame subgraphs ({len(frames_data)} frames)...")
    for f_data in frames_data:
        ft = f_data.get("frame_token", "?")
        # 构建帧级子数据
        sub_data = {
            "meta": data.get("meta", {}),
            "global_critical_scores": data.get("global_critical_scores", []),
            "frames": [f_data],
            "nodes": f_data.get("nodes", []),
            "edges": f_data.get("edges", []),
        }
        fname = os.path.join(OUT_DIR, f"graph_frame_{ft}.dot")
        export_dot(sub_data, fname, max_nodes=top_k,
                  label=f"Frame {ft}", mode="per_frame")

if __name__ == "__main__":
    main()
